class CssLocators:

    hillel_mail_css_locator = """$$("a[class*='contacts_link h4']")"""
    footer_logo_css_locator = """$$("a[class*='footer_logo']")"""
    login_form_header_4_css_locator = """$$("h4[class='modal-title']")"""
    signin_email_label_css_locator = """$$("label[for='signinEmail']")"""
    email_input_css_locator = """$$("input[id='signinEmail']")"""
    signin_password_label_css_locator = """$$("label[for='signinPassword']")"""
    password_input_css_locator = """$$("input[id='signinPassword']")"""
    remember_me_checkbox_css_locator = """$$("input[type='checkbox']")"""
    remember_me_text_css_locator = """$$("label[for='remember']")"""
    registration_button_css_locator = """$$("button[type='button'][class='btn btn-link']")"""
    h1_header_css_locator = """$("h1")"""
    add_car_button_css_locator = """$$("button.btn.btn-primary")"""
    brand_label_css_locator = """$$("label[for='addCarBrand']")"""
    brand_select_css_locator = """$$("select#addCarBrand")"""
    model_label_css_locator = """$$("label[for='addCarModel']")"""
    model_select_css_locator = """$$("select#addCarModel")"""
    mileage_label_css_locator = """$$("label[for='addCarMileage']")"""
    mileage_select_css_locator = """$$("select#addCarMileage")"""
    add_button_css_locator = """$$("button[type='button'][class='btn btn-primary']")"""
    cancel_button_css_locator = """$$("button[type='button'][class='btn btn-secondary']")"""
    garage_button_css_locator = """$$("a[routerlink='/panel/garage'][class*='btn header-link']")"""
    fuel_expenses_button_css_locator = """$$("a[routerlink='/panel/expenses'][class*='btn header-link']")"""
    instructions_button_css_locator = """$$("a[routerlink='/panel/instructions'][class*='btn header-link']")"""
    my_profile_dropdown_css_locator = """$$("button#userNavDropdown")"""
    my_profile_dropdown_logout_button_css_locator = """$$("button.dropdown-item.btn.btn-link.user-nav_link")"""