class XpathLocators:

    iframe_xpath_locator = """$x("//iframe[@class='hero-video_frame']")"""
    sign_up_button_class_xpath_locator = """$x("//button[@class='hero-descriptor_btn btn btn-primary']")"""
    sign_up_button_text_xpath_locator = """$x("//button[text()='Sign up']")"""
    text_title_xpath_locator = """$x("//h1[text()='Do more!']")"""
    text_descr_xpath_locator = """$x("//p[contains(text(),'With the help of')]")"""
    home_button_xpath_locator = """$x("//a[@class='btn header-link -active']")"""
    about_button_xpath_locator = """$x("//button[@class='btn header-link' and @appscrollto='aboutSection']")"""
    contacts_button_xpath_locator = """$x("//button[@class='btn header-link' and @appscrollto='contactsSection']")"""
    guest_log_in_button_xpath_locator = """$x("//button[@class='header-link -guest']")"""
    sign_in_button_xpath_locator = """$x("//button[text()='Sign In']")"""
    about_pic_1_xpath_locator = """$x("(//img[@class='about-picture_img'])[1]")"""
    about_text_1_header_xpath_locator = """$x("//p[contains(text(),'Log fuel')]")"""
    about_block_1_xpath_locator = """$x("(//p[@class='about-block_descr lead'])[1]")"""
    about_pic_2_xpath_locator = """$x("(//img[@class='about-picture_img'])[last()]")"""
    about_text_2_header_xpath_locator = """$x("//p[contains(text(),'Instructions and')]")"""
    about_block_2_xpath_locator = """$x("(//p[@class='about-block_descr lead'])[last()]")"""
    contacts_xpath_locator = """$x("//h2[(text()='Contacts')]")"""
    facebook_icon_xpath_locator = """$x("(//span[contains(@class,'icon-facebook')])")"""
    telegram_icon_xpath_locator = """$x("(//span[contains(@class,'icon-telegram')])")"""
    youtube_icon_xpath_locator = """$x("(//span[contains(@class,'icon-youtube')])")"""
    instagram_icon_xpath_locator = """$x("(//span[contains(@class,'icon-instagram')])")"""
    linkedin_icon_xpath_locator = """$x("(//span[contains(@class,'icon-linkedin')])")"""
    hillel_website_xpath_locator = """$x("(//a[@class='contacts_link display-4'])")"""
    footer_text_1_xpath_locator = """$x("//p[contains(text(),'2021 Hillel')]")"""
    footer_text_2_xpath_locator = """$x("//p[contains(text(),'Hillel auto developed')]")"""